- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: First Scene
  items:
    - label: "First Things on the Screen"
      link: "/first-scene/first-render"
    - label: "Lights"
      link: "/first-scene/lights"
    - label: "Animation"
      link: "/first-scene/animation"
- label: API
  items:
    - label: "Canvas"
      link: "/api/canvas"
    - label: "Objects and properties"
      link: "/api/objects-and-properties"
    - label: "Automatic disposal"
      link: "/api/automatic-disposal"
    - label: "Events"
      link: "/api/events"
    - label: "Hooks"
      items:
        - label: "useThree"
          link: "/api/hooks/useThree"
    - label: "Additional exports"
      link: "/api/additional"

- label: Recipes
  items:
    - label: "Animating with react-spring"
      link: "/recipes/animating-with-react-spring"
    - label: "Dealing with effects"
      link: "/recipes/dealing-with-effects-hijacking-main-render-loop"
    - label: "Using your own camera rig"
      link: "/recipes/using-your-own-camera-rig"
    - label: "Enabling VR"
      link: "/recipes/enabling-vr"
    - label: "Heads-up display"
      link: "/recipes/heads-up-display-rendering-multiple-scenes"
    - label: "Managing imperative code"
      link: "/recipes/managing-imperative-code"
    - label: "Re-parenting"
      link: "/recipes/re-parenting"
    - label: "Reducing bundle-size"
      link: "/recipes/reducing-bundle-size"
    - label: "Rendering only when needed"
      link: "/recipes/rendering-only-when-needed"
    - label: "Shader Materials"
      link: "/recipes/shader-materials"
    - label: "Switching the default renderer"
      link: "/recipes/switching-the-default-renderer"
    - label: "Usage with React Native"
      link: "/recipes/usage-with-react-native"
